### ISSUE TITLE
 CUDA cannot be initialized correctly

### ISSUE THREAD

**Issue by xingxingjiukunkun** [mxhulab/cryopros#13]
My command is
  nohup cryopros-train --opt /public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.1/site-packages/cryoPROS/options/train.json --gpu_ids 0 1 --task_name HA_iteration_1 --box_size 256 --Apix 1.31 --volume_scale 50 --init_volume_path 6idd_align_lp10.mrc --data_path T00_HA_130K-Equalized-Particle-Stack.mrcs --param_path autorefinement.star --invert --dataloader_batch_size 8 > output.log 2>&1
but i got problem:
     Traceback (most recent call last):
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/bin/cryopros-train", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "cryoPROS/main_train.py", line 138, in cryoPROS.main_train.main
  File "cryoPROS/models/model_hvae.py", line 22, in cryoPROS.models.model_hvae.HVAEModel.__init__
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 312, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

  File "/public/apps/em/yes/envs/CRYOPROS_ENV/bin/cryopros-train", line 5, in <module>
    from cryoPROS.main_train import main
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1296, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/__init__.py", line 1478, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 238, in <module>
    _lazy_call(_check_capability)
  File "/public/apps/em/yes/envs/CRYOPROS_ENV/lib/python3.12/site-packages/torch/cuda/__init__.py", line 235, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

**Comment by zhengdharia** [comment]
Can you try adding
```
export WORLD_SIZE=2
```
before running the command?
